title: AaltoSEA current deadlines
description: Countdowns to Heaven or Valhalla.
#source from: Bogdan Kulynych
author: hong3nguyen

domain: "https://hong3nguyen.github.io"
baseurl: "/academic-deadlines"

twitter_username: hong3nguyen
github_username: hong3nguyen
github_repo: academic-deadlines
ga_id: UA-104921371-1

markdown: kramdown
